name: appfirmarpdf
description: "App para firmar PDFs con código de referido local"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ==== Firebase ====
  firebase_core:   ^3.13.0
  firebase_auth:   ^5.5.2
  cloud_firestore: ^5.6.6   # si lo usas

  # ==== File Picker ====
  # Volvemos a la serie 6.x que usa web:^0.5.x, compatible con firebase_auth_web
  file_picker: ^10.1.2

  # ==== Resto de tu app ====
  shared_preferences:              ^2.1.1
  syncfusion_flutter_pdfviewer:    ^29.1.39
  syncfusion_flutter_pdf:          ^29.1.39
  signature:                       ^5.3.0
  syncfusion_flutter_signaturepad: ^29.1.39
  path_provider:                   ^2.1.2
  share_plus:                      ^7.2.1
  universal_html:                  ^2.2.4
  flutter_form_builder:            ^10.0.1
  url_launcher:                    ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
